### ISSUE TITLE
Deploy to https://app.cyclic.sh/ After the above, the backend can access the front end 404

### ISSUE THREAD

**Issue by wu529778790** [szymmis/vite-express#75]
![image](https://github.com/szymmis/vite-express/assets/11481938/6e916e2a-3e6f-4574-a990-69f2c02ebbd5)

**Comment by szymmis** [comment]
Hi @wu529778790, it looks like you should set "Serve output as static" as true.
Also make sure that the output path is accurate, if you use the defaults `/dist` is correct.

As soon as you make the changes and save them, just make another commit to the main branch and everything should be working fine. That's what I did when testing this out and it did worked indeed.

Let me know if that works for you, thanks for raising this issue!

**Comment by wu529778790** [comment]
> Hi @wu529778790, it looks like you should set "Serve output as static" as true. Also make sure that the output path is accurate, if you use the defaults `/dist` is correct.
> 
> As soon as you make the changes and save them, just make another commit to the main branch and everything should be working fine. That's what I did when testing this out and it did worked indeed.
> 
> Let me know if that works for you, thanks for raising this issue!

Thank you, but it still doesn't work. Every time I save it, I go back in and the settings are reset again

**Comment by wu529778790** [comment]
> Hi @wu529778790, it looks like you should set "Serve output as static" as true. Also make sure that the output path is accurate, if you use the defaults `/dist` is correct.
> 
> As soon as you make the changes and save them, just make another commit to the main branch and everything should be working fine. That's what I did when testing this out and it did worked indeed.
> 
> Let me know if that works for you, thanks for raising this issue!

https://github.com/wu529778790/FullStackBlog

https://good-erin-stingray-yoke.cyclic.app/

**Comment by szymmis** [comment]
Are you sure that you commited after saving changes to trigger redeploy? Maybe that's the case?

**Comment by szymmis** [comment]
It seems like you dont have more questions, so I'll proceed and close this issue. If you have anything you want to ask, feel free to continue this thread.
